### ISSUE TITLE
Santander payment methods are not rendered on the frontend if Santander Rechnungskauf is disabled

### ISSUE THREAD

**Issue by ptylek** [patworx-de/santander-magento-2#2]
Issue:
santander_invoice is not properly added to XML layout, therefore if Santander Ratenkauf is not active in Admin Panel, js component will not load on the frontend in the Checkout and Santander Rechnungskauf will not be visible.

Actual:
In admin panel, you can enable Santander Ratenkauf only and have it display properly on the frontend.

In admin panel, you can enable both Santander Ratenkauf and Santander Rechnungskauf and have them both visible on the frontend.

In admin panel, you can not enable Santander Rechnungskauf only. It won't be visible on the frontend.

Solution:
Update XML to include both payment methods properly.

**Comment by ptylek** [comment]
@mkreusch I prepared solution: [Update checkout_index_index.xml](https://github.com/patworx-de/santander-magento-2/pull/1) #1

**Comment by mkreusch** [comment]
Thanks for sharing your solution! We finally merged it.
