### ISSUE TITLE
Unable to complete Santander Rechnungskauf payment

### ISSUE THREAD

**Issue by ptylek** [patworx-de/santander-magento-2#3]
Set age below 18 years old. Click place order.
After some time default error message appears.

Then change age above 18 years old. Click place order again.
After some time default error message appears.

It is not possible to complete checkout if customer selects wrong date on his first attempt.
Customer won’t be able to complete payment with Santander Ratenkauf, too.
Customer won't be able to complete checkout.

**Comment by mkreusch** [comment]
Hi!

Unfortunately we were not able to reproduce this. However, we added an age check before submission so this cannot happen anymore.
