### ISSUE TITLE
Unable to complete Santander Ratenkauf payment

### ISSUE THREAD

**Issue by ptylek** [patworx-de/santander-magento-2#4]
Set age below 18 years old. Select payment plan. Click place order.

Checkout will be stuck at loading screen and the server responded with a status of 500 () will be displayed in console log.
Customer won’t be able to complete the checkout at all.

**Comment by mkreusch** [comment]
Hi!

Unfortunately we were not able to reproduce this. However, we added an age check before submission so this cannot happen anymore.
