### ISSUE TITLE
Santander payments are not available

### ISSUE THREAD

**Issue by ptylek** [patworx-de/santander-magento-2#5]
Fill in company field in Shipping Address (Step 1 of the checkout).
Santander payments won’t be available.

**Comment by mkreusch** [comment]
Hi Paweł,

thanks for opening all that useful issues ans the PR.
I will try to get to this asap.

This is the only one that is not an issue but the desired behavior: Santander payments shall never be available to companies.

Best regards
Marcus

**Comment by ptylek** [comment]
Marcus,
Thanks for your reply.
BR
